[project]
name = "gemini-mcp-example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-genai>=1.11.0",
    "mcp>=1.6.0",
    "python-dotenv>=1.1.0",
]

[tool.ruff]
indent-width = 2
line-length = 120
